# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipDenucia', models.CharField(choices=[(b'AC', b'Abandono en la Calle'), (b'ETE', b'Exposici\xc3\xb3n a Temperaturas Extremas'), (b'FA', b'Falta de Agua'), (b'FC', b'Falta de Comida'), (b'V', b'Violencia'), (b'VA', b'Venta Ambulante')], max_length=3)),
                ('Animal', models.CharField(choices=[(b'Perro', b'Perro'), (b'Gato', b'Gato'), (b'Otro', b'Otro')], max_length=10)),
                ('Sexo', models.CharField(choices=[(b'H', b'Hembra'), (b'M', b'Macho')], max_length=1)),
                ('Color', models.CharField(max_length=10)),
                ('Comentario', models.CharField(max_length=30)),
            ],
        ),
    ]
