# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLeyCholito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='Animal',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='Sexo',
            field=models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho')], max_length=1),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='TipDenucia',
            field=models.CharField(choices=[('AC', 'Abandono en la Calle'), ('ETE', 'Exposición a Temperaturas Extremas'), ('FA', 'Falta de Agua'), ('FC', 'Falta de Comida'), ('V', 'Violencia'), ('VA', 'Venta Ambulante')], max_length=3),
        ),
    ]
