# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLeyCholito', '0002_auto_20171003_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('password_repeat', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[(b'PN', b'Persona Natural'), (b'RM', b'Representante de Municipalidad')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='TipDenucia',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='Herido',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='TipDenuncia',
            field=models.CharField(choices=[(b'AC', b'Abandono en la Calle'), (b'ETE', b'Exposici\xc3\xb3n a Temperaturas Extremas'), (b'FA', b'Falta de Agua'), (b'FC', b'Falta de Comida'), (b'V', b'Violencia'), (b'VA', b'Venta Ambulante')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
