# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLeyCholito', '0002_auto_20171003_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('password_repeat', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('PN', 'Persona Natural'), ('RM', 'Representante de Municipalidad')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='TipDenucia',
            new_name='TipDenuncia',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='Herido',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
