# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLeyCholito', '0003_auto_20171011_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='user_type',
            field=models.CharField(choices=[('PN', 'Persona Natural'), ('RM', 'Representante de Municipalidad')], max_length=1),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='TipDenuncia',
            field=models.CharField(choices=[('AC', 'Abandono en la Calle'), ('ETE', 'Exposición a Temperaturas Extremas'), ('FA', 'Falta de Agua'), ('FC', 'Falta de Comida'), ('V', 'Violencia'), ('VA', 'Venta Ambulante')], max_length=3),
        ),
    ]
