# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLeyCholito', '0004_auto_20171019_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='Estado_Denuncia',
            field=models.CharField(choices=[(b'reportadas', b'reportadas'), (b'consolidadas', b'consolidadas'), (b'verificadas', b'verificadas'), (b'cerradas', b'cerradas'), (b'desechadas', b'desechadas')], default=123456789, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='TipDenuncia',
            field=models.CharField(choices=[(b'AC', b'Abandono en la Calle'), (b'ETE', b'Exposici\xc3\xb3n a Temperaturas Extremas'), (b'FA', b'Falta de Agua'), (b'FC', b'Falta de Comida'), (b'V', b'Violencia'), (b'VA', b'Venta Ambulante')], max_length=3),
        ),
    ]
