# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLeyCholito', '0011_remove_animal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='Foto',
            field=models.ImageField(default=b'in.jpeg', upload_to=b'AppLeyCholito/images'),
        ),
    ]
