# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLeyCholito', '0016_auto_20171021_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Foto',
            field=models.ImageField(default='in.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Sexo',
            field=models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho')], max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Tipo',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='user_type',
            field=models.CharField(choices=[('PN', 'Persona Natural'), ('RM', 'Representante de Municipalidad'), ('RO', 'Representante de Organizacion'), ('ADM', 'Administrador')], max_length=1),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='Estado_Denuncia',
            field=models.CharField(choices=[('reportadas', 'reportadas'), ('consolidadas', 'consolidadas'), ('verificadas', 'verificadas'), ('cerradas', 'cerradas'), ('desechadas', 'desechadas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='TipDenuncia',
            field=models.CharField(choices=[('AC', 'Abandono en la Calle'), ('ETE', 'Exposicion a Temperaturas Extremas'), ('FA', 'Falta de Agua'), ('FC', 'Falta de Comida'), ('V', 'Violencia'), ('VA', 'Venta Ambulante')], max_length=3),
        ),
    ]
