# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLeyCholito', '0017_auto_20171023_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='Edad_Estimda',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='animal',
            name='En_adopcion_desde',
            field=models.DateField(default=datetime.date(2017, 10, 23)),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Foto',
            field=models.ImageField(default=b'in.jpeg', upload_to=b'AppLeyCholito/static/AppLeyCholito/imgs_animales'),
        ),
    ]
