# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLeyCholito', '0018_auto_20171023_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Foto',
            field=models.ImageField(default='in.jpeg', upload_to='AppLeyCholito/static/AppLeyCholito/imgs_animales'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='Estado_Denuncia',
            field=models.CharField(choices=[('Reportadas', 'Reportadas'), ('Consolidadas', 'Consolidadas'), ('Verificadas', 'Verificadas'), ('Cerradas', 'Cerradas'), ('Desechadas', 'Desechadas')], max_length=10),
        ),
    ]
